name: Terraform OCI Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. OCI Key Setup
      - name: Setup OCI Authentication
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          echo "Key fingerprint:"
          openssl rsa -in ~/.oci/oci_api_key.pem -pubout -outform DER 2>/dev/null | openssl md5 -c

      # 2. Terraform Setup
      - uses: hashicorp/setup-terraform@v2

      # 3. Terraform Commands
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: |
          terraform plan -input=false \
            -var="tenancy_ocid=${{ secrets.TF_VAR_TENANCY_OCID }}" \
            -var="user_ocid=${{ secrets.TF_VAR_USER_OCID }}" \
            -var="fingerprint=${{ secrets.TF_VAR_FINGERPRINT }}" \
            -var="region=${{ secrets.TF_VAR_REGION }}" \
            -var="compartment_id=${{ secrets.TF_VAR_COMPARTMENT_ID }}" \
            -var="subnet_id=${{ secrets.TF_VAR_SUBNET_OCID }}"